name: Artifacts Workflow

on:
  push:

jobs:
    artifacts:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning Repo code to runner
              uses: actions/checkout@v4

            - name: Create a file
              run: echo "This is an artifact file." > artifact.txt

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: my-artifact
                path: artifact.txt