name: Docker login Workflow
on:
  push:

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin