name: First CI/CD Pipeline

on:
    push:

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
            - name: Run Command hello world
              run: |
               echo "Hello guys this is my first pipeline, github action is working!!"
               ls
               mkdir Test
               ls
               uname -a
               whoami
               date
               echo "Completed"
               pwd