name: First CI/CD Pipeline

on:
  push:

env:
    name: Practice
    APP: Frontend

jobs:

    Run:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning Repo code to runner
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            - name: Run Command hello world
              run: |
                echo "Hello guys this is my first pipeline, github action is working!!"
                echo "App: ${APP}"


    test:
        runs-on: windows-latest
        needs: Run
        steps:
            - name: Usage of need keyword
              if: github.ref == 'master'
              run: |
                echo "This step will run after the Run job is completed."