name: Reusable Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      name:
        required: true
        type: string
      APP:
        required: true
        type: string

env:
    name: ${{ inputs.name }}
    APP: ${{ inputs.APP }}

jobs:
  Run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        username: [kapil, john, jane]
        python-version: [3.11, 3.12]


    steps:
      - name: Cloning Repo code to runner
        uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: install flake8
        run: pip install flake8

      - name: Run flake8
        run: |
          flake8 app.py
          echo "App: ${APP} && Name: ${name} with the username: ${{ matrix.username }}"