name: Reusable Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      name:
        required: true
        type: string
      APP:
        required: true
        type: string

env:
    name: ${{ inputs.name }}
    APP: ${{ inputs.APP }}

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo code to runner
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: install flake8
        run: pip install flake8

      - name: Run flake8
        run: |
          flake8 app.py
          echo "App: ${APP} && Name: ${name}"